### ISSUE TITLE
pip install Error

### ISSUE THREAD

**Issue by yangsp5** [kyegomez/LongNet#21]
when pip install, it got wrong:

```
Collecting git+https://github.com/kyegomez/LongNet.git
  Cloning https://github.com/kyegomez/LongNet.git to /tmp/pip-req-build-z5f85jrm
  Running command git clone --filter=blob:none --quiet https://github.com/kyegomez/LongNet.git /tmp/pip-req-build-z5f85jrm
  Resolved https://github.com/kyegomez/LongNet.git to commit a621fc8ed60520ee90bafee4ab26c13ea8bec19e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-3lxviw8j/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/api.py", line 42, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "/tmp/pip-build-env-3lxviw8j/overlay/local/lib/python3.10/dist-packages/poetry/core/factory.py", line 58, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - data.documentation must be uri
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/LongNet/issues/21">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/LongNet/issues/21/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/LongNet/issues/21/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@yangsp5 Thanks for bringing this to my attention, I have fixed it by specifying docs url!
