### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by jmanhype** [kyegomez/LongNet#3]
:~/LongNet$ pip install -r requirements.txt
Requirement already satisfied: torch in /home/straughterguthrie/robust/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.0.1)
Collecting einops
  Using cached einops-0.6.1-py3-none-any.whl (42 kB)
Collecting flash_attn
  Using cached flash_attn-1.0.8.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/straughterguthrie/robust/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/straughterguthrie/robust/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/straughterguthrie/robust/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-tjgu9b0f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-tjgu9b0f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-tjgu9b0f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(robust) straughterguthrie@straughterguthrie-OMEN-by-HP-Obelisk-Desktop-875-1xxx:~/LongNet$

**Comment by jmanhype** [comment]
It looks like the issue might be with the `flash_attn` package itself or with its requirements during the build process. Since your environment seems to satisfy all required dependencies (including PyTorch), this might be something the creators of `flash_attn` need to correct on their end. 

You could raise an issue on the project's GitHub repository to see if there's a known resolution. This kind of error could be due to many factors, but common ones are:

- The package might not be compatible with your specific configuration.
- "ModuleNotFoundError: No module named 'torch'" suggests the building process is looking for `torch` and not finding it. This could be an issue on the project build's end.
  
In the meantime, if it is not critical to your work, you might want to look for alternative packages that have similar functionality to `flash_attn`. 

Lastly, you can fork the repository and fix the problem, but this could be time-consuming and requires a deep understanding of the codebase. 

I want to assure you that the problem seems not to be on your side but with the package build system itself. You should definitely write an issue on the original `flash_attn` repository describing the problem and also showing that torch is indeed installed and available by running and showing this output:
  
```linux
python -c "import torch; print(torch.__version__)"
```
python -c "import torch; print(torch.__version__)"
2.0.1+cu117

**Comment by josedandrade** [comment]
Right. After reading requirements.txt decided to 

pip install git+https://github.com/HazyResearch/flash-attention.git

And it is stuck...15 minutes building wheels for collected packages: flash-attn and counting.

**Comment by kyegomez** [comment]
@josedandrade @jmanhype Hey 👋 please try pip installing again, I put the wrong flash attention pip name

**Comment by wywzxxz** [comment]
Not work.
`pip install flash-attn  -i https://pypi.org/simple/ --no-cache-dir `

```
Looking in indexes: https://pypi.org/simple/
Collecting flash-attn
  Downloading flash_attn-1.0.8.tar.gz (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 4.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/wywzxxz/miniconda3/envs/privateGPT/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/wywzxxz/miniconda3/envs/privateGPT/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/wywzxxz/miniconda3/envs/privateGPT/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-uh_xq5kl/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-uh_xq5kl/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-uh_xq5kl/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by jmanhype** [comment]
Still not working please help

**Comment by jmanhype** [comment]
Tried on windows and linux

**Comment by wywzxxz** [comment]
The problem is from flash-attn
See 
https://github.com/HazyResearch/flash-attention/issues/258
and 
https://github.com/HazyResearch/flash-attention/issues/246


`pip install flash-attn==1.0.5 ` should fix this

**Comment by AK51** [comment]
I cannot find the folder... flash_attn


    Prepare flash_attn library
```
cd flash_attn

python setup.py install

cd ..
```

**Comment by kyegomez** [comment]
@AK51 hey we removed the flash_attn repo, were now using our flash implementation in LongNet/attend

**Comment by AK51** [comment]
Hi, thanks for your reply.
I git clone again, and use the original LongNet  env, but there is another error of LongNet.torchscale
...
I really want to try LongNet.... Thx
```
LongNet$ pip install -r requirements.txt
Requirement already satisfied: torch in /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: einops in /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.6.1)
Requirement already satisfied: accelerate in /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (0.20.3)
Requirement already satisfied: bitsandbytes in /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.39.1)
Requirement already satisfied: fairscale in /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.4.0)
Requirement already satisfied: timm in /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (0.6.13)
Requirement already satisfied: ninja in /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (1.11.1)
Requirement already satisfied: packaging in /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (23.1)
Requirement already satisfied: transformers in /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/transformers-4.30.2-py3.9.egg (from -r requirements.txt (line 9)) (4.30.2)
ERROR: Could not find a version that satisfies the requirement unittest (from versions: none)
ERROR: No matching distribution found for unittest

```

```
python -m unittest

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/ak/anaconda3/envs/LongNet/lib/libcudart.so'), PosixPath('/home/ak/anaconda3/envs/LongNet/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/ak/anaconda3/envs/LongNet/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
E
======================================================================
ERROR: LongNet (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: LongNet
Traceback (most recent call last):
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/media/ak/HD/LongNet/LongNet/__init__.py", line 2, in <module>
    from LongNet.model import LongNetTokenizer, LongNet, DecoderConfig, Decoder, DilatedLongNet
  File "/media/ak/HD/LongNet/LongNet/model.py", line 3, in <module>
    import bitsandbytes
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/optim/__init__.py", line 8, in <module>
    from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/optim/adagrad.py", line 5, in <module>
    from bitsandbytes.optim.optimizer import Optimizer1State
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/optim/optimizer.py", line 12, in <module>
    import bitsandbytes.functional as F
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/functional.py", line 12, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
(LongNet) ak@ak-MS-7D99:/media/ak/HD/LongNet$ pip install scipy
Collecting scipy
  Downloading scipy-1.11.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.5/36.5 MB 5.7 MB/s eta 0:00:00
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages (from scipy) (1.25.0)
Installing collected packages: scipy
Successfully installed scipy-1.11.1
(LongNet) ak@ak-MS-7D99:/media/ak/HD/LongNet$ python -m unittest

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/ak/anaconda3/envs/LongNet/lib/libcudart.so.11.0'), PosixPath('/home/ak/anaconda3/envs/LongNet/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/ak/anaconda3/envs/LongNet/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
E
======================================================================
ERROR: LongNet.torchscale (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: LongNet.torchscale
Traceback (most recent call last):
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/home/ak/anaconda3/envs/LongNet/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/media/ak/HD/LongNet/LongNet/torchscale/__init__.py", line 3, in <module>
    from torchscale.architecture.decoder import DecoderConfig, Decoder
ImportError: cannot import name 'DecoderConfig' from 'torchscale.architecture.decoder' (/home/ak/anaconda3/envs/LongNet/lib/python3.9/site-packages/torchscale-0.2.0-py3.9.egg/torchscale/architecture/decoder.py)


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
