### ISSUE TITLE
Any demo python I can play with?

### ISSUE THREAD

**Issue by AK51** [kyegomez/LongNet#5]
Hi,

I have installed LongNet in my Ubuntu,
but when I type python example.py, there is error...
```
python example.py 
Traceback (most recent call last):
  File "........../LongNet/example.py", line 3, in <module>
    from LongNet import DilatedAttention
  File "........../LongNet/LongNet/__init__.py", line 6, in <module>
    from LongNet.attention import DilatedAttention
  File "........../LongNet/LongNet/attention.py", line 6, in <module>
    from LongNet.torchscale import XPOS, RelativePositionBias
ImportError: cannot import name 'XPOS' from 'LongNet.torchscale' (unknown location)

```
I am still reading the github and the paper, is there any demo python program I can play with first? Thx

**Comment by kuehno** [comment]
@AK51 
I was having the same issue initially. When installing LongNet using pip, it will also install torchscale. In the LongNet repository however, torchscale is forked and modified slightly in the __init__.py. 

See original __init__.py from torchscale: https://github.com/microsoft/torchscale/blob/main/torchscale/__init__.py

In order to fix it you would need to clone the LongNet repository (which contains the respective changes) or clone + install torchscale to your working directory and modify the __init__.py yourself.

**Comment by AK51** [comment]
Mm... I tried to clone the LongNet repo again but I can not find 
cd flash_attn

May I have a straight forward installation instruction. Thx I can wait.

**Comment by kyegomez** [comment]
@kuehno Yeah torchscale was a big issue, we've fixed that now.

And, @AK51 and yeah we removed it as we made our own custom implementation for flash attention here:
https://github.com/kyegomez/LongNet/blob/master/LongNet/attend.py
