### ISSUE TITLE
RuntimeError: shape '[32, 1, -1, 64, 512]' is invalid for input of size 524288

### ISSUE THREAD

**Issue by One-sixth** [kyegomez/LongNet#8]
Hello, thank your great work.
I try to run example_main.py. Then raise error.
It looks like the length of the input sequence must be a multiple of dilation_rate * segment_size .
```python
Traceback (most recent call last):
  File "D:\github_repo\LongNet\example_main.py", line 35, in <module>
    _ = attention(x)
        ^^^^^^^^^^^^
  File "Z:\Software\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github_repo\LongNet\LongNet\attention.py", line 88, in forward
    x_ = x_.contiguous().view(batch_size, 1, -1, self.segment_size, self.d_model)  # Add an extra dimension for the number of heads
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[32, 1, -1, 64, 512]' is invalid for input of size 524288
```

**Comment by kyegomez** [comment]
@One-sixth Hey this has been patched, this was shaping error. Let me know if it works for you!
